In [40]:
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from pandas import DataFrame, Timestamp

import akshare as ak
import pandas as pd

CHINA_TZ = ZoneInfo("Asia/Shanghai")

In [41]:
tool_trade_date_hist_sina_df = ak.tool_trade_date_hist_sina()
print(tool_trade_date_hist_sina_df.dtypes)
tool_trade_date_hist_sina_df.tail(10)

trade_date    object
dtype: object

      trade_date
8545  2025-12-18
8546  2025-12-19
8547  2025-12-22
8548  2025-12-23
8549  2025-12-24
8550  2025-12-25
8551  2025-12-26
8552  2025-12-29
8553  2025-12-30
8554  2025-12-31

In [42]:
tool_trade_date_hist_sina_df['trade_date'] = pd.to_datetime(tool_trade_date_hist_sina_df['trade_date']).dt.tz_localize(CHINA_TZ)
tool_trade_date_hist_sina_df.dtypes

trade_date    datetime64[ns, Asia/Shanghai]
dtype: object

In [43]:
tool_trade_date_hist_sina_df.tail(10)

                    trade_date
8545 2025-12-18 00:00:00+08:00
8546 2025-12-19 00:00:00+08:00
8547 2025-12-22 00:00:00+08:00
8548 2025-12-23 00:00:00+08:00
8549 2025-12-24 00:00:00+08:00
8550 2025-12-25 00:00:00+08:00
8551 2025-12-26 00:00:00+08:00
8552 2025-12-29 00:00:00+08:00
8553 2025-12-30 00:00:00+08:00
8554 2025-12-31 00:00:00+08:00

In [44]:
datetime_now: datetime = pd.to_datetime(datetime.now(tz=CHINA_TZ)).replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1)
# 筛选出小于当前时间的交易日
matches: DataFrame = tool_trade_date_hist_sina_df.loc[tool_trade_date_hist_sina_df['trade_date'] < datetime_now]
# 筛选出最近的两天 (索引越大离现在越近)
matches: DataFrame = matches.tail(2).reset_index()

matches

   index                trade_date
0   8421 2025-06-19 00:00:00+08:00
1   8422 2025-06-20 00:00:00+08:00

In [45]:
by_trade_date: Timestamp = matches.at[0, 'trade_date']
y_trade_date: Timestamp = matches.at[1, 'trade_date']

In [46]:
byd_data: DataFrame = ak.get_futures_daily(start_date=by_trade_date.strftime("%Y%m%d"), end_date=by_trade_date.strftime("%Y%m%d"), market='CZCE')
byd_data

,symbol,date,open,high,low,close,volume,open_interest,turnover,settle,pre_settle,variety
0,AP510,20250619,7665.0,7687.0,7577.0,7608.0,60999,90416,464762.97,7619.0,7654.0,AP
1,AP511,20250619,7514.0,7514.0,7425.0,7455.0,158,4558,1179.65,7466.0,7489.0,AP
2,AP512,20250619,7508.0,7511.0,7453.0,7473.0,37,182,276.57,7475.0,7506.0,AP
3,AP601,20250619,7543.0,7550.0,7464.0,7490.0,1977,10311,14825.14,7499.0,7528.0,AP
4,AP603,20250619,7536.0,7550.0,7502.0,7505.0,18,127,135.43,7524.0,7538.0,AP
...,...,...,...,...,...,...,...,...,...,...,...,...
228,ZC602,20250619,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
229,ZC603,20250619,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
230,ZC604,20250619,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
231,ZC605,20250619,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
232,ZC606,20250619,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC

In [47]:
yd_data: DataFrame = ak.get_futures_daily(start_date=y_trade_date.strftime("%Y%m%d"), end_date=y_trade_date.strftime("%Y%m%d"), market='CZCE') # type: ignore
yd_data

,symbol,date,open,high,low,close,volume,open_interest,turnover,settle,pre_settle,variety
0,AP510,20250620,7613.0,7786.0,7609.0,7731.0,127565,107930,985659.18,7727.0,7619.0,AP
1,AP511,20250620,7455.0,7630.0,7455.0,7567.0,279,4532,2113.15,7574.0,7466.0,AP
2,AP512,20250620,7517.0,7624.0,7517.0,7582.0,41,155,310.16,7565.0,7475.0,AP
3,AP601,20250620,7483.0,7666.0,7480.0,7592.0,5689,10589,43266.97,7605.0,7499.0,AP
4,AP603,20250620,7575.0,7668.0,7571.0,7594.0,15,124,114.26,7618.0,7524.0,AP
...,...,...,...,...,...,...,...,...,...,...,...,...
228,ZC602,20250620,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
229,ZC603,20250620,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
230,ZC604,20250620,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
231,ZC605,20250620,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC
232,ZC606,20250620,0.0,0.0,0.0,0.0,0,0,0.00,801.4,801.4,ZC