In [17]:
from datetime import datetime
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
from pandas import DataFrame

from vnpy.trader.constant import (Direction, Exchange, Offset, OptionType,
                                  OrderType, Product, Status)
from vnpy.trader.object import (CancelRequest, OrderData, PositionData,
                                TickData, TradeData)

In [18]:
order_info_cols: dict[str, str] = {
    "symbol": 'string',
    "vt_symbol": 'string',
    "datetime": 'datetime64[ns, Asia/Shanghai]',
    "canceltime": 'datetime64[ns, Asia/Shanghai]',
    "exchange": 'object',  # enum: Exchange
    "ordersysid": 'string',
    "status": 'object',  # enum: Status
    "direction": 'object',  # enum: Direction
    "offset": 'object',  # enum: Offset
    "price": 'float64',
    "type": 'object',  # enum: OrderType
    "volume": 'float64',
    "traded": 'float64',
    "memo": 'string'
}

# 使用 order_info_columns 定义 DataFrame 的列类型
order_info: DataFrame = DataFrame(columns=list(order_info_cols.keys())).astype(order_info_cols)

In [19]:
order_info

Empty DataFrame
Columns: [symbol, vt_symbol, datetime, canceltime, exchange, ordersysid, status, direction, offset, price, type, volume, traded, memo]
Index: []

In [20]:
order_info.dtypes

symbol                       string[python]
vt_symbol                    string[python]
datetime      datetime64[ns, Asia/Shanghai]
canceltime    datetime64[ns, Asia/Shanghai]
exchange                             object
ordersysid                   string[python]
status                               object
direction                            object
offset                               object
price                               float64
type                                 object
volume                              float64
traded                              float64
memo                         string[python]
dtype: object

In [21]:
CHINA_TZ = ZoneInfo("Asia/Shanghai")

# 随机生成一些 OrderData, 放到 order_data_list 中
order_data_list = [OrderData(
        symbol=f"IF{i+1:04d}",
        exchange=Exchange.CFFEX,
        orderid=f"a_{i+1:03d}_123",
        ordersysid=f"{i+1:010d}",
        direction=Direction.LONG if i % 2 == 0 else Direction.SHORT,
        offset=Offset.OPEN if i % 2 == 0 else Offset.CLOSE,
        price=3000.0 + i * 10,
        volume=1.0 + i * 0.1,
        type=OrderType.LIMIT,
        status=Status.NOTTRADED if i % 3 != 0 else Status.ALLTRADED,
        datetime=datetime.now().replace(tzinfo=CHINA_TZ),
        gateway_name="CTP",
    ) for i in range(10)]

In [22]:
order_data_list[0].__dict__

{'gateway_name': 'CTP',
 'symbol': 'IF0001',
 'exchange': <Exchange.CFFEX: 'CFFEX'>,
 'orderid': 'a_001_123',
 'ordersysid': '0000000001',
 'type': <OrderType.LIMIT: '限价'>,
 'direction': <Direction.LONG: '多'>,
 'offset': <Offset.OPEN: '开'>,
 'price': 3000.0,
 'volume': 1.0,
 'traded': 0,
 'status': <Status.ALLTRADED: '全部成交'>,
 'datetime': datetime.datetime(2025, 6, 18, 10, 37, 38, 800475, tzinfo=zoneinfo.ZoneInfo(key='Asia/Shanghai')),
 'reference': '',
 'canceltime': None,
 'memo': '',
 'vt_symbol': 'IF0001.CFFEX',
 'vt_orderid': 'CTP.a_001_123'}

In [23]:
df = pd.concat(
    objs=[
        order_info,
        DataFrame(data=order_data_list, columns=list(order_info_cols.keys()))
    ],
    ignore_index=True)
# df = df.astype(order_info_cols)
df

,symbol,vt_symbol,datetime,canceltime,exchange,ordersysid,status,direction,offset,price,type,volume,traded,memo
0,IF0001,NaN,2025-06-18 10:37:38.800475+08:00,None,Exchange.CFFEX,0000000001,Status.ALLTRADED,Direction.LONG,Offset.OPEN,3000.0,OrderType.LIMIT,1.0,0.0,
1,IF0002,NaN,2025-06-18 10:37:38.800487+08:00,None,Exchange.CFFEX,0000000002,Status.NOTTRADED,Direction.SHORT,Offset.CLOSE,3010.0,OrderType.LIMIT,1.1,0.0,
2,IF0003,NaN,2025-06-18 10:37:38.800490+08:00,None,Exchange.CFFEX,0000000003,Status.NOTTRADED,Direction.LONG,Offset.OPEN,3020.0,OrderType.LIMIT,1.2,0.0,
3,IF0004,NaN,2025-06-18 10:37:38.800493+08:00,None,Exchange.CFFEX,0000000004,Status.ALLTRADED,Direction.SHORT,Offset.CLOSE,3030.0,OrderType.LIMIT,1.3,0.0,
4,IF0005,NaN,2025-06-18 10:37:38.800495+08:00,None,Exchange.CFFEX,0000000005,Status.NOTTRADED,Direction.LONG,Offset.OPEN,3040.0,OrderType.LIMIT,1.4,0.0,
5,IF0006,NaN,2025-06-18 10:37:38.800497+08:00,None,Exchange.CFFEX,0000000006,Status.NOTTRADED,Direction.SHORT,Offset.CLOSE,3050.0,OrderType.LIMIT,1.5,0.0,
6,IF0007,NaN,2025-06-18 10:37:38.800498+08:00,None,Exchange.CFFEX,0000000007,Status.ALLTRADED,Direction.LONG,Offset.OPEN,3060.0,OrderType.LIMIT,1.6,0.0,
7,IF0008,NaN,2025-06-18 10:37:38.800500+08:00,None,Exchange.CFFEX,0000000008,Status.NOTTRADED,Direction.SHORT,Offset.CLOSE,3070.0,OrderType.LIMIT,1.7,0.0,
8,IF0009,NaN,2025-06-18 10:37:38.800501+08:00,None,Exchange.CFFEX,0000000009,Status.NOTTRADED,Direction.LONG,Offset.OPEN,3080.0,OrderType.LIMIT,1.8,0.0,
9,IF0010,NaN,2025-06-18 10:37:38.800503+08:00,None,Exchange.CFFEX,0000000010,Status.ALLTRADED,Direction.SHORT,Offset.CLOSE,3090.0,OrderType.LIMIT,1.9,0.0,

In [24]:
df.dtypes

symbol         object
vt_symbol      object
datetime       object
canceltime     object
exchange       object
ordersysid     object
status         object
direction      object
offset         object
price         float64
type           object
volume        float64
traded        float64
memo           object
dtype: object

In [25]:
df

,symbol,vt_symbol,datetime,canceltime,exchange,ordersysid,status,direction,offset,price,type,volume,traded,memo
0,IF0001,NaN,2025-06-18 10:37:38.800475+08:00,None,Exchange.CFFEX,0000000001,Status.ALLTRADED,Direction.LONG,Offset.OPEN,3000.0,OrderType.LIMIT,1.0,0.0,
1,IF0002,NaN,2025-06-18 10:37:38.800487+08:00,None,Exchange.CFFEX,0000000002,Status.NOTTRADED,Direction.SHORT,Offset.CLOSE,3010.0,OrderType.LIMIT,1.1,0.0,
2,IF0003,NaN,2025-06-18 10:37:38.800490+08:00,None,Exchange.CFFEX,0000000003,Status.NOTTRADED,Direction.LONG,Offset.OPEN,3020.0,OrderType.LIMIT,1.2,0.0,
3,IF0004,NaN,2025-06-18 10:37:38.800493+08:00,None,Exchange.CFFEX,0000000004,Status.ALLTRADED,Direction.SHORT,Offset.CLOSE,3030.0,OrderType.LIMIT,1.3,0.0,
4,IF0005,NaN,2025-06-18 10:37:38.800495+08:00,None,Exchange.CFFEX,0000000005,Status.NOTTRADED,Direction.LONG,Offset.OPEN,3040.0,OrderType.LIMIT,1.4,0.0,
5,IF0006,NaN,2025-06-18 10:37:38.800497+08:00,None,Exchange.CFFEX,0000000006,Status.NOTTRADED,Direction.SHORT,Offset.CLOSE,3050.0,OrderType.LIMIT,1.5,0.0,
6,IF0007,NaN,2025-06-18 10:37:38.800498+08:00,None,Exchange.CFFEX,0000000007,Status.ALLTRADED,Direction.LONG,Offset.OPEN,3060.0,OrderType.LIMIT,1.6,0.0,
7,IF0008,NaN,2025-06-18 10:37:38.800500+08:00,None,Exchange.CFFEX,0000000008,Status.NOTTRADED,Direction.SHORT,Offset.CLOSE,3070.0,OrderType.LIMIT,1.7,0.0,
8,IF0009,NaN,2025-06-18 10:37:38.800501+08:00,None,Exchange.CFFEX,0000000009,Status.NOTTRADED,Direction.LONG,Offset.OPEN,3080.0,OrderType.LIMIT,1.8,0.0,
9,IF0010,NaN,2025-06-18 10:37:38.800503+08:00,None,Exchange.CFFEX,0000000010,Status.ALLTRADED,Direction.SHORT,Offset.CLOSE,3090.0,OrderType.LIMIT,1.9,0.0,

### GroupBy

In [26]:
speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0),
        ("bird", "Psittaciformes", 24.0),
        ("mammal", "Carnivora", 80.2),
        ("mammal", "Primates", np.nan),
        ("mammal", "Carnivora", 58),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)

In [27]:
speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [28]:
speeds.dtypes

class         object
order         object
max_speed    float64
dtype: object

In [29]:
grouped = speeds.groupby(by="class")
group: DataFrame
for name, g in grouped:  # 每个 group (DataFrame) 都是一个 copy
    print(name)
    group = g

group.loc['lion', 'max_speed'] = 999.0  # 修改 copy 不会影响原始 speeds
group

bird
mammal

          class      order  max_speed
lion     mammal  Carnivora      999.0
monkey   mammal   Primates        NaN
leopard  mammal  Carnivora       58.0

In [30]:
speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [48]:
speeds.loc[speeds['order'] == 'Falconiformes', 'max_speed'].item()

389.0

In [34]:
df_from_dict = DataFrame(
    data={'a': 1, 'b': 2, 'c': 3},
    index=[0]
)
df_from_dict  # 修改 DataFrame 中的值

   a  b  c
0  1  2  3

In [37]:
from datetime import timedelta
dt = pd.Timestamp("2023-10-01 12:00:00", tz=CHINA_TZ)
dt = dt + pd.Timedelta(days=1)
dt

Timestamp('2023-10-02 12:00:00+0800', tz='Asia/Shanghai')

In [52]:
ts = pd.Timestamp("2023-10-01 12:00:00", tz=CHINA_TZ) + pd.Timedelta(seconds=10)
ts

Timestamp('2023-10-01 12:00:10+0800', tz='Asia/Shanghai')

In [71]:
df_dt_test = DataFrame(
    {
        'a': [1, 2],
        'dt_with_tz': [pd.Timestamp("2023-10-01 12:00:00", tz=CHINA_TZ), pd.Timestamp("2023-10-01 12:00:00", tz=CHINA_TZ)],
    }
)
df_dt_test

   a                dt_with_tz
0  1 2023-10-01 12:00:00+08:00
1  2 2023-10-01 12:00:00+08:00

In [69]:
df_dt_test.dtypes

a                                     int64
dt_with_tz    datetime64[ns, Asia/Shanghai]
dtype: object

In [70]:
df_mask = df_dt_test['a'] % 2 == 0
df_dt_test['dt_without_tz'] = pd.NaT
df_dt_test.loc[df_mask, 'dt_without_tz'] = df_dt_test.loc[df_mask, 'dt_with_tz'] + pd.Timedelta(days=1)

### 从 list of dict 构建一个 DataFrame

In [78]:
df_from_dict_list = DataFrame(
    data=[
        {'a': 1, 'b': 2, 'c': 3},
        {'a': 4, 'b': 5, 'c': 6},
    ],
)
df_from_dict_list

   a  b  c
0  1  2  3
1  4  5  6

In [79]:
df_from_dict_list.dtypes

a    int64
b    int64
c    int64
dtype: object

### 先定义 DataFrame (带 columns) 然后 concat 一个只有部分 columns 的 DataFrame

In [93]:
df_with_cols = DataFrame(columns=['a', 'b', 'c']).astype({'a': 'int', 'b': 'int', 'c': 'int'})
df_with_cols = pd.concat([df_with_cols, DataFrame([{'a': 1, 'b': 2, 'c': 3}])], ignore_index=True)
print(df_with_cols.dtypes)
print(df_with_cols)

a    int64
b    int64
c    int64
dtype: object
   a  b  c
0  1  2  3