In [4]:
from datetime import datetime
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
from pandas import DataFrame

from vnpy.trader.constant import (Direction, Exchange, Offset, OptionType,
                                  OrderType, Product, Status)
from vnpy.trader.object import (CancelRequest, OrderData, PositionData,
                                TickData, TradeData)

In [5]:
CHINA_TZ = ZoneInfo("Asia/Shanghai")

###

In [6]:
df_dt_test = DataFrame(
    {
        'a': [1, 2, 3],
        'dt_with_tz': [pd.Timestamp("2023-10-01 12:00:00", tz=CHINA_TZ), pd.Timestamp("2023-10-02 12:00:00", tz=CHINA_TZ), pd.Timestamp("2023-10-03 12:00:00", tz=CHINA_TZ)],
    }
)
df_dt_test

   a                dt_with_tz
0  1 2023-10-01 12:00:00+08:00
1  2 2023-10-02 12:00:00+08:00
2  3 2023-10-03 12:00:00+08:00

In [7]:
df_dt_test.dtypes

a                                     int64
dt_with_tz    datetime64[ns, Asia/Shanghai]
dtype: object

In [8]:
df_dt_test['dt_without_tz'] = pd.Series(pd.NaT, dtype="datetime64[ns, Asia/Shanghai]")  # ⚠️如果要创建 pd.NaT 一定要显式的指定时区!!!
df_dt_test

   a                dt_with_tz dt_without_tz
0  1 2023-10-01 12:00:00+08:00           NaT
1  2 2023-10-02 12:00:00+08:00           NaT
2  3 2023-10-03 12:00:00+08:00           NaT

In [9]:
df_dt_test.dtypes

a                                        int64
dt_with_tz       datetime64[ns, Asia/Shanghai]
dt_without_tz    datetime64[ns, Asia/Shanghai]
dtype: object

In [10]:
df_mask = df_dt_test['a'] % 2 == 0
df_dt_test.loc[df_mask, 'dt_without_tz'] = df_dt_test.loc[df_mask, 'dt_with_tz'] + pd.Timedelta(days=1)
df_dt_test

   a                dt_with_tz             dt_without_tz
0  1 2023-10-01 12:00:00+08:00                       NaT
1  2 2023-10-02 12:00:00+08:00 2023-10-03 12:00:00+08:00
2  3 2023-10-03 12:00:00+08:00                       NaT